### ISSUE TITLE
Fonction et variable portant le même nom

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/Utils-Flask-SQLAlchemy-Geo#25]
Cette ligne https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/blob/develop/src/utils_flask_sqla_geo/serializers.py#L94
lève l'erreur : `local variable 'shape' referenced before assignment`

**Comment by camillemonchicourt** [comment]
Intégré dans la 0.3.0
