### ISSUE TITLE
GenericQueryGeo doesn't redefine 'return_query'

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/Utils-Flask-SQLAlchemy-Geo#30]
## Problème
Relation d'héritage entre `GenericQueryGeo` et `GenericQuery,` centrée sur la méthode `GenericQueryGeo` hérite de `GenericQuery`, mais ne redéfinit pas la méthode `return_query`.

> Dans le module export, on crée un objet `GenericQueryGeo` et on appelle la méthode `return_query`.
> Le `return_query` fait appel à la query non géo définit dans `GenericQuery`.
> On pourrait faire un fix en appelant `as_geofeature` au lieu de `render_query`, mais il semble que ça ne correspond pas au comportement attendu.
> ![image](https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/assets/150020787/4109791d-5963-44ae-b176-54a3efb20e59)
> ![image](https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/assets/150020787/644b2173-2f63-4dc4-b203-8d6cd16c22ae)

## Proposition
A priori, il me semble que l'on pourrait faire les modifications suivantes: 
- Création de la méthode "return_query", qui surchargerait la méthode _return_query_ de `GenericQuery`
  Cette méthode ferait un truc genre:
  ```python
     def return_query(self):
        if self.geometry_field:
            return self.as_geofeature()
        else:
            return super(GenericQueryGeo, self).return_query()
  ```

La méthode `as_geofeature` pourrait être limitée au cas de geometry_field définit, ou alors conservée en l'état par soucis de rétrocompatibilité. 

Qu'est-ce que vous en pensez ?

**Comment by edelclaux** [comment]
up

**Comment by TheoLechemia** [comment]
Oui Ok pour moi

**Comment by edelclaux** [comment]
> Oui Ok pour moi

Ca marche ! J'avais un peu râté la notif on dirait :)

**Comment by edelclaux** [comment]
Up, avec PR à la clef ;)
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/pull/33

**Comment by bouttier** [comment]
Ça me semble pas extraordinaire d’avoir une fonction dont on ne sait pas trop quel va être le format de retour. Par ailleurs, il n’est plus possible d’obtenir les données dans le format de 'return_query` même si c’est ce que l’on souhaite … De mon avis, c’est à l’utilisateur d’appeler `as_geofeature` ou `return_query` suivant le format des données qu’il veut. Et donc il faudrait plutôt corriger le module d’export. C’est ce qui est fait par exemple ici : https://github.com/PnX-SI/gn_module_export/blob/f48b65e9a61df18bd18c1c9d326dd167b90ecf93/backend/gn_module_export/repositories.py#L101-L104
Et de manière général il faudrait supprimer `return_query` car non scalable … (cf workshop ayant amené à la version 1.5 du module).

**Comment by edelclaux** [comment]
ça veux dire qu'il faut clore la PR et reprendre le truc ?

**Comment by edelclaux** [comment]
ça peut aussi être une erreur à lever, du genre "geometry is not defined". 
Est-ce qu'un objet "**GenericQueryGeo** sans geometry a du sens ?

Dans le lien que tu as partagé: si on demande un `geofeature` mais qu'on a pas de `geometry_field`, on se retrouve quand même avec un `return_query`. C'est lisible comme format de retour ça ? C'est le même "problème" non ?

**Comment by bouttier** [comment]
Oui je suis d’accord avec toi c’est le même problème : ihmo, on devrait avoir une 404 si on demande une geofeature sur un export sans géométrie. Le problème avec ce genre de fallback, c’est qu’un utilisateur de l’API va envoyer la réponse du serveur dans son parser de geojson et ça va planter …

Une GenericQueryGeo sans geometry n’a pas beaucoup de sens, mais pourrait pourquoi pas exister, à condition qu’un appelle à as_geofeature renvoie une erreur si pas de geom.
D’ailleurs je vois que le code de as_geofeature fait un fallback sur as_dict au lieu de as_geofeature si pas de geom, et je pense que c’est une mauvaise idée pour les mêmes raisons.

**Comment by bouttier** [comment]
Je ne retrouve pas dans le code du module d’export l’utilisation qui te posais problème. C’est encore d’actualité ?
De préférence met des permaliens (ils peuvent référencer plusieurs lignes !) plutôt que des captures d’écran !

**Comment by edelclaux** [comment]
> Je mets la PR en draft

Il y a différents type de personne, certains préfèrent avoir tout les chunks de code sous yeux :)

Lien vers l'appel en question: 
https://github.com/PnX-SI/gn_module_export/blob/200c12f68d508dc09f6c57c8abc832cea89f55d5/backend/gn_module_export/blueprint.py#L292C1-L295C32

qui gère la query retournée par la route: https://github.com/PnX-SI/gn_module_export/blob/1b8145bb50cb77bf8f658f048501ab33960c01c2/backend/gn_module_export/blueprint.py#L197C1-L302C16

La méthode "get_view_query" (la mal-nommée :) ) est un builder de `GenericQueryGeo`.
Ca donne l'impression qu'il y a des traces d'une tentative de polymorphisme.

https://github.com/PnX-SI/gn_module_export/blob/200c12f68d508dc09f6c57c8abc832cea89f55d5/backend/gn_module_export/models.py#L140C1-L149C10

Si je résume concrètement, il faut choisir entre ces options: 

Option 1: 
- conserver la surcharge de "return_query" dans `Utils-Flask-SQLAlchemy-Geo` (en remplaçant le fallback vers le return_query du parent par un raise d'erreur)
- mettre le if geometry/else dans "get_view_query" du module export

Option 2: 
- ne rien toucher à `Utils-Flask-SQLAlchemy-Geo`, c'est à dire pas de surcharge de "return_query"
- mettre le if geometry/else dans "get_one_export_api" du module export

Option 3:
- conserver la surcharge de "return_query" dans `Utils-Flask-SQLAlchemy-Geo`

Option D: 
- la réponse D

**Comment by bouttier** [comment]
Arf en effet github n’affiche pas le code quand il réside dans un autre dépôt …

Option 2 il me semble :

Il ne faut pas surcharger `return_query` et garder l’implémentation du parent afin de pouvoir, si on le souhaite, récupérer les données au format json, même si on utilise `GenericQueryGeo`.

Que la route `get_one_export_api` renvoi « aléatoirement » du json ou du geojson me semble pas ouf, mais bon, considérant ce comportement, c’est bien là qu’il faut rajouter un contrôle pour appeler `as_geofeature` ou `return_query` suivant le cas.

Il n’y a peu d’intérêt à modifier `get_view_query` : renvoyer une `GenericQueryGeo` même en l’absence de colonne géométrique n’est pas un problème (tant qu’on n’appelle pas `as_geofeature`).

**Comment by edelclaux** [comment]
Ca me va. J'ai décalé l'issue dans le bon projet pour la peine. 

[#214](https://github.com/PnX-SI/gn_module_export/issues/214)

**Comment by edelclaux** [comment]
Issue [#214](https://github.com/PnX-SI/gn_module_export/issues/214)
PR [#215](https://github.com/PnX-SI/gn_module_export/pull/215)
