### ISSUE TITLE
Géométries ponctuelles simples et multiples et SHP

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/Utils-Flask-SQLAlchemy-Geo#5]
Un fichier SHP ne peut pas mélanger des points simples et multiples (https://trac.osgeo.org/gdal/ticket/3677). Du coup il est proposé de forcer les géométries ponctuelles simples en multiples, au cas où un export contiendrait des géométries simples et des multiples de même type.

Fait ici : https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/commit/ec00bca0a946ad883efde27c73dedec032066578

Par contre pas utile et dommage de la faire aussi sur le GeoPackage ?

**Comment by amandine-sahl** [comment]
Cette conversion n'est réalisée que sur le shape file. Elle est assurée par la méthode `write_a_feature` qui est une méthode abstraite.

**Comment by camillemonchicourt** [comment]
Fait dans la version 0.1.0
